# Generated by Django 2.2 on 2021-04-16 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(max_length=1000)),
                ('form_description', models.CharField(max_length=2000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_title', models.CharField(max_length=1000)),
                ('ques_type', models.CharField(choices=[('', 'Select'), ('SH', 'Short'), ('SC', 'Single Choice'), ('MC', 'Multiple Choice')], default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoogleForm.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('ques', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GoogleForm.Question')),
            ],
        ),
    ]
